DesafioBiblioteca/Models/ErrorViewModel.cs
namespace DesafioBiblioteca.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DesafioBiblioteca/Models/Livro.cs
using System.ComponentModel.DataAnnotations;

namespace DesafioBiblioteca.Models
{
    public class Livro
    {
        public int Id { get; set; }
        [Display(Name = "Título")]
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public int Ano { get; set; }
        [Display(Name = "Gênero")]
        public Genero Genero { get; set; }

        public bool Emprestado { get; set; }
    }

    public enum Genero
    {
        Conto, 
        Fantasia, 
        [Display(Name = "Ficção Científica")] FiccaoCientifica, 
        Poesia,
        Romance  
    }
}

DesafioBiblioteca/Controllers/HomeController.cs
using DesafioBiblioteca.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DesafioBiblioteca.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DesafioBiblioteca/Controllers/LivroController.cs
using DesafioBiblioteca.Models;
using Microsoft.AspNetCore.Mvc;

namespace DesafioBiblioteca.Controllers
{
    public class LivroController : Controller
    {
        public static List<Livro> _livros = new List<Livro>();
        private static int _id = 0;
        public IActionResult Index()
        {
            ViewBag.livros = _livros;
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Livro livro)
        {
            livro.Id = ++_id;
            livro.Emprestado = false;
            _livros.Add(livro);
            TempData["msg"] = "Livro cadastrado com sucesso!";
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            Livro livro = _livros.Find(l => l.Id == id);
            return View(livro);
        }

        [HttpPost]
        public IActionResult Editar(Livro livro)
        {
            _livros[_livros.FindIndex(l => l.Id == livro.Id)] = livro;
            TempData["msg"] = "Livro editado com sucesso!";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Remover(int Id)
        {
            _livros.RemoveAll(l => l.Id == Id);
            TempData["msg"] = "Livro removido com sucesso!";
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Emprestar(int id)
        {
            _livros[_livros.FindIndex(l => l.Id == id)].Emprestado = true;
            TempData["msg"] = "Livro emprestado com sucesso!";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Devolver(int id)
        {
            _livros[_livros.FindIndex(l => l.Id == id)].Emprestado = false;
            TempData["msg"] = "Livro devolvido com sucesso!";
            return RedirectToAction("Emprestado");
        }

        public IActionResult Emprestado()
        {
            return View(_livros);
        }

    }
}

DesafioBiblioteca/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Biblioteca";
}

<div class="text-center">
    <h1 class="display-4">Bem-vindo(a) a biblioteca</h1>

    <a asp-controller="Livro" asp-action="Index">

        <div class="d-grid gap-2">
            <button class="btn btn-primary" type="button">Consulte o acervo</button>
        </div>

    </a>

    <img class="img-fluid" src="~/img/livros.jpg" />

</div>

DesafioBiblioteca/Views/Livro/Editar.cshtml
@model Livro
@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<form asp-action=Editar>
    <partial name="_Form" />
    <input type="submit" value="Salvar" class="btn btn-primary"/>

</form>

DesafioBiblioteca/Views/Livro/Emprestado.cshtml
@model List<Livro>;
@{
    ViewData["Title"] = "Emprestado";
}

<h1>Livros Emprestados</h1>

<a asp-action="Index" type="button" class="btn btn-primary">Voltar para o acervo</a>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

@if (Model.Count > 0)
{
    <table class="table">
        <tr class="table-light text-center">
            <th>Id</th>
            <th>Título</th>
            <th>Autor</th>
            <th>Ano</th>
            <th>Gênero</th>
            <th>Ações</th>
        </tr>

        @foreach (Livro livro in Model)
        {
            if (livro.Emprestado == true)
            {
              <tr class="text-center">
                <td>@livro.Id</td>
                <td>@livro.Titulo</td>
                <td>@livro.Autor</td>
                <td>@livro.Ano</td>
                <td>@livro.Genero</td>
                <td>
                    <a asp-action="Devolver" asp-route-id="@livro.Id" class="btn btn-sm btn-success">Devolver</a>
                </td>
                
            </tr>  
            }
            

        }


    </table>

}
else
{
    <div class="alert alert-dark">
        Acervo vazio
    </div>
}

DesafioBiblioteca/Views/Livro/Index.cshtml
@model Livro

@{
    ViewData["Title"] = "Index";
}

<h1>Acervo de livros</h1>



@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}


<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#CadastroModal">
    
    Cadastrar novo livro

    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z" />
    </svg>

    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
        <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"></path>
    </svg>
</button>


@if (ViewBag.livros.Count > 0)
{
    <table class="table">
        <tr class="table-light text-center">
            <th>Id</th>
            <th>Título</th>
            <th>Autor</th>
            <th>Ano</th>
            <th>Gênero</th>
            <th>Ações</th>
            <th>Status</th>
        </tr>

        @foreach (Livro livro in ViewBag.livros)
        {
            <tr class="text-center">
                <td>@livro.Id</td>
                <td>@livro.Titulo</td>
                <td>@livro.Autor</td>
                <td>@livro.Ano</td>
                <td>@livro.Genero</td>
                <td>
                    <a asp-action="Editar" asp-route-id="@livro.Id" class="btn btn-sm btn-warning">Editar</a>

                    <button onclick="idLivro.value = @livro.Id" type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#RemoverModal">
                        Remover
                    </button>

                </td>
                <td>
                    @if (@livro.Emprestado == false)
                    {
                        <div class="btn btn-sm btn-info" readonly>Disponível</div>
                        <a asp-action="Emprestar" asp-route-id="@livro.Id" class="btn btn-sm btn-success">Emprestar</a>
                    }
                    else
                    {
                        <a asp-action="Emprestado" class="btn btn-sm btn-info">Emprestado</a>
                       
                    }
                </td>
            </tr>

        }


    </table>

}
else
{
    <div class="alert alert-dark">
        Acervo vazio
    </div>
}

<!-- Modal cadastro livro -->
<div class="modal fade" id="CadastroModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form asp-action=Cadastrar>
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Cadastrar novo livro</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <partial name="_Form" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                    <input type="submit" value="Cadastrar" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>


<!-- Modal remover livro -->
<div class="modal fade" id="RemoverModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Remover livro</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Deseja remover o livro selecionado do acervo?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <form asp-action="Remover">
                    <input type="hidden" name="id" id="idLivro" />
                    <input type="submit" class="btn btn-primary" value="Remover" />
                </form>
            </div>
        </div>
    </div>
</div>

DesafioBiblioteca/Views/Livro/_Form.cshtml
@model Livro

<div class="mb-3">
    <label asp-for="Titulo" class="form-label"></label>
    <input asp-for="Titulo" class="form-control" />
</div>

<div class="mb-3">
    <label asp-for="Autor" class="form-label"></label>
    <input asp-for="Autor" class="form-control" />
</div>

<div class="mb-3">
    <label asp-for="Ano" class="form-label"></label>
    <input asp-for="Ano" class="form-control" />
</div>

<div class="mb-3">
    <label asp-for="Genero" class="form-label"></label>
    <select asp-for="Genero" class="form-select" asp-items="@Html.GetEnumSelectList<Genero>()"></select>
</div>

DesafioBiblioteca/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DesafioBiblioteca</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DesafioBiblioteca.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DesafioBiblioteca</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Livro" asp-action="Index">Acervo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Livro" asp-action="Emprestado">Livros emprestados</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DesafioBiblioteca - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>